### ISSUE TITLE
`Attestations Created` output should be improved

### ISSUE THREAD

**Issue by stdedos** [actions/attest-build-provenance#155]
The dynamic output format that looks like

```md
<h3>Attestations Created</h3>
<a href="https://github.com/a/b/attestations/1368115">b_ SNAPSHOT-v0.4.0-1-g2246b21_Darwin_arm64.tar.gz@sha256:509</a>
<a href="https://github.com/a/b/attestations/1368116">b_ SNAPSHOT-v0.4.0-1-g2246b21_Darwin_x86_64.tar.gz@sha256:e80</a>
<a href="https://github.com/a/b/attestations/1368117">b_ SNAPSHOT-v0.4.0-1-g2246b21_Linux_arm64.tar.gz@sha256:b24</a>
<a href="https://github.com/a/b/attestations/1368118">b_ SNAPSHOT-v0.4.0-1-g2246b21_Linux_i386.tar.gz@sha256:103</a>
<a href="https://github.com/a/b/attestations/1368119">b_ SNAPSHOT-v0.4.0-1-g2246b21_Linux_x86_64.tar.gz@sha256:37d</a>
<a href="https://github.com/a/b/attestations/1368120">b_ SNAPSHOT-v0.4.0-1-g2246b21_Windows_arm64.zip@sha256:714</a>
<a href="https://github.com/a/b/attestations/1368121">b_ SNAPSHOT-v0.4.0-1-g2246b21_Windows_i386.zip@sha256:036</a>
<a href="https://github.com/a/b/attestations/1368122">b_ SNAPSHOT-v0.4.0-1-g2246b21_Windows_x86_64.zip@sha256:2ac</a>
```
does not render "correctly" even on Github-commonmark

<h3>Attestations Created</h3>
<a href="https://github.com/a/b/attestations/1368115">b_ SNAPSHOT-v0.4.0-1-g2246b21_Darwin_arm64.tar.gz@sha256:509</a>
<a href="https://github.com/a/b/attestations/1368116">b_ SNAPSHOT-v0.4.0-1-g2246b21_Darwin_x86_64.tar.gz@sha256:e80</a>
<a href="https://github.com/a/b/attestations/1368117">b_ SNAPSHOT-v0.4.0-1-g2246b21_Linux_arm64.tar.gz@sha256:b24</a>
<a href="https://github.com/a/b/attestations/1368118">b_ SNAPSHOT-v0.4.0-1-g2246b21_Linux_i386.tar.gz@sha256:103</a>
<a href="https://github.com/a/b/attestations/1368119">b_ SNAPSHOT-v0.4.0-1-g2246b21_Linux_x86_64.tar.gz@sha256:37d</a>
<a href="https://github.com/a/b/attestations/1368120">b_ SNAPSHOT-v0.4.0-1-g2246b21_Windows_arm64.zip@sha256:714</a>
<a href="https://github.com/a/b/attestations/1368121">b_ SNAPSHOT-v0.4.0-1-g2246b21_Windows_i386.zip@sha256:036</a>
<a href="https://github.com/a/b/attestations/1368122">b_ SNAPSHOT-v0.4.0-1-g2246b21_Windows_x86_64.zip@sha256:2ac</a>

(for posterity:)
![image](https://github.com/user-attachments/assets/dc49271d-53e6-49a5-a060-3392af7b9dc4)

Its output should be improved - but I cannot find where is it coming from:

* It's not from this repo https://github.com/search?q=repo%3Aactions%2Fattest-build-provenance%20Attestations%20Created&type=code
* Or its "binary": https://github.com/search?q=repo%3Aactions%2Ftoolkit%20Attestations%20Created&type=code

**Comment by bdehamer** [comment]
This should be fixed with the [1.4.0](https://github.com/actions/attest-build-provenance/releases/tag/v1.4.0) release
