### ISSUE TITLE
Attestations are printed twice?

### ISSUE THREAD

**Issue by stdedos** [actions/attest-build-provenance#176]
https://github.com/stdedos/junit2html/actions/runs/10125546240

e.g. `0ae969cc78c6482b50ffafaa3d8875ebf5da011c70bf69305cf286f1517e5313` appears twice, but only once in the run logs

**Comment by bdehamer** [comment]
@stdedos it looks like you have the same path listed twice when you invoke `actions/attest-build-provenance`:

https://github.com/stdedos/junit2html/actions/runs/10125546240/workflow#L55-L57

This will result in all of your artifacts being attested twice.

**Comment by phillmv** [comment]
This sounds like it was addressed. Closing issue out,
