### ISSUE TITLE
Error: InternalError: error creating signing certificate - FetchError: network timeout at: https://fulcio.sigstore.dev/api/v2/signingCert

### ISSUE THREAD

**Issue by ukd1** [actions/attest-build-provenance#194]
[Error: InternalError: error creating signing certificate
FetchError: network timeout at: https://fulcio.sigstore.dev/api/v2/signingCert](https://github.com/ukd1/canonical-rails/actions/runs/10297484219/job/28501683951#step:6:31)

this was working, but now isn't.

I see some "2 minutes" of downtime on the [status page for sigstore.dev](https://status.sigstore.dev)....but,it says all are ok, but also some red, and I can't see any detail.

<img width="818" alt="image" src="https://github.com/user-attachments/assets/59eebdea-c759-4131-a123-5f1db654bd92">

no incidents reported:
<img width="1087" alt="image" src="https://github.com/user-attachments/assets/d3cfb3cc-ec63-4056-9a3d-7aa65b861591">

**Comment by pwelch** [comment]
@ukd1 There was a temporary issue with the Sigstore Public Good database that required manual intervention by the Sigstore on-call engineer but has been resolved. An update has been published to the Sigstore status page: https://status.sigstore.dev/incident/410910

**Comment by ukd1** [comment]
@pwelch thanks - so just a delay in posting about the incident?

thoughts about integrating something into the action that can either check, or suggest manual checking of the status page if this kinda failure happens? (i.e. internal ones, 500s, etc)

**Comment by pwelch** [comment]
@ukd1 Yeah

> thoughts about integrating something into the action that can either check, or suggest manual checking of the status page if this kinda failure happens? (i.e. internal ones, 500s, etc)

That's an interesting idea, we'll consider that as a future enhancement.

**Comment by julywint007** [comment]
> [Error: InternalError: error creating signing certificate FetchError: network timeout at: https://fulcio.sigstore.dev/api/v2/signingCert](https://github.com/ukd1/canonical-rails/actions/runs/10297484219/job/28501683951#step:6:31)
> 
> this was working, but now isn't.
> 
> I see some "2 minutes" of downtime on the [status page for sigstore.dev](https://status.sigstore.dev)....but,it says all are ok, but also some red, and I can't see any detail.
> 
> <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/44345/356126818-59eebdea-c759-4131-a123-5f1db654bd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDQ1OTIsIm5iZiI6MTcyMzI0NDI5MiwicGF0aCI6Ii80NDM0NS8zNTYxMjY4MTgtNTllZWJkZWEtYzc1OS00MTMxLWExMjMtNWYxZGI2NTRiZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIyNTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDQ0NjU3NjUwZjhkZTUwMWJjMDNlZDI5NGI2ZDEwNTUwZTcxOTIxMWM3MmEwNzdjMzhmMzM4YWM4MGMzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4KuwjqgSp_ztMZHTGNdLvcfK3oY1iUMWr5Hg3rFA3E">
> no incidents reported: <img alt="image" width="1087" src="https://private-user-images.githubusercontent.com/44345/356127184-d3cfb3cc-ec63-4056-9a3d-7aa65b861591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDQ1OTIsIm5iZiI6MTcyMzI0NDI5MiwicGF0aCI6Ii80NDM0NS8zNTYxMjcxODQtZDNjZmIzY2MtZWM2My00MDU2LTlhM2QtN2FhNjViODYxNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIyNTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Zjc0MTU1MzI4Yjk0NmEwZmJmMDRhZWZlN2E0OTQ3NGI5ZTk1ZmE0NmFhMGJjMjk3MTRiMGI5YjRkZDNhYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XUW3p0zCaD2fa2BB59BU3jCRQytpDDuSVIMppdytGTU">

**Comment by julywint007** [comment]
> > [Error: InternalError: error creating signing certificate FetchError: network timeout at: https://fulcio.sigstore.dev/api/v2/signingCert](https://github.com/ukd1/canonical-rails/actions/runs/10297484219/job/28501683951#step:6:31)
> > this was working, but now isn't.
> > I see some "2 minutes" of downtime on the [status page for sigstore.dev](https://status.sigstore.dev)....but,it says all are ok, but also some red, and I can't see any detail.
> > <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/44345/356126818-59eebdea-c759-4131-a123-5f1db654bd92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDQ1OTIsIm5iZiI6MTcyMzI0NDI5MiwicGF0aCI6Ii80NDM0NS8zNTYxMjY4MTgtNTllZWJkZWEtYzc1OS00MTMxLWExMjMtNWYxZGI2NTRiZDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIyNTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNDQ0NjU3NjUwZjhkZTUwMWJjMDNlZDI5NGI2ZDEwNTUwZTcxOTIxMWM3MmEwNzdjMzhmMzM4YWM4MGMzMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4KuwjqgSp_ztMZHTGNdLvcfK3oY1iUMWr5Hg3rFA3E">
> > no incidents reported: <img alt="image" width="1087" src="https://private-user-images.githubusercontent.com/44345/356127184-d3cfb3cc-ec63-4056-9a3d-7aa65b861591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDQ1OTIsIm5iZiI6MTcyMzI0NDI5MiwicGF0aCI6Ii80NDM0NS8zNTYxMjcxODQtZDNjZmIzY2MtZWM2My00MDU2LTlhM2QtN2FhNjViODYxNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIyNTgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2Zjc0MTU1MzI4Yjk0NmEwZmJmMDRhZWZlN2E0OTQ3NGI5ZTk1ZmE0NmFhMGJjMjk3MTRiMGI5YjRkZDNhYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XUW3p0zCaD2fa2BB59BU3jCRQytpDDuSVIMppdytGTU">
