### ISSUE TITLE
our guide on how to mark your work with a CC license

### ISSUE THREAD

**Issue by ratchanonsuttawas** [actions/attest-build-provenance#269]
https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

**Comment by ratchanonsuttawas** [comment]
> https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license

**Comment by ratchanonsuttawas** [comment]
> > https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license
> 
>

**Comment by KING-GHUB** [comment]
https://www.tiktok.com/@itsmemoe10?_t=8qDJd7PAqmG&_r=1
