### ISSUE TITLE
Feature request  - output the Github attestation page URL

### ISSUE THREAD

**Issue by mendhak** [actions/attest-build-provenance#311]
Currently the action is able to output the sigstore bundle path. 

Please also add the attestation URL as an output. 

For example: https://github.com/mendhak/gpslogger/attestations/2943251

**Comment by mendhak** [comment]
Wonderful, thank you!

**Comment by bdehamer** [comment]
Feature added in [v2.1.0](https://github.com/actions/attest-build-provenance/releases/tag/v2.1.0) release.

**Comment by ETEnterprises1** [comment]
edge://blank=bank%20of%20montreal%20financial%20group%20united%20states/@ETEnterprises1//github.com/etenterprises1\\bmo.com

**Comment by ETEnterprises1** [comment]
`git request push`> edge://blank=bank%20of%20montreal%20financial%20group%20united%20states/@ETEnterprises1//github.com/etenterprises1\\bmo.com

**Comment by ETEnterprises1** [comment]
@ETEnterprises1 ![Screenshot_20250102-124931.png](https://github.com/user-attachments/assets/062159ec-8209-477a-a295-ad887738d1a5)

> `git request push`> edge://blank=bank%20of%20montreal%20financial%20group%20united%20states/@ETEnterprises1//github.com/etenterprises1\\bmo.com
> 
>
