### ISSUE TITLE
Failed to persist attestation: Server Error

### ISSUE THREAD

**Issue by martincostello** [actions/attest-build-provenance#396]
After ingesting a dependabot PR to update to v2 of the action (https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/pull/253) the build [failed to attest our artifacts](https://github.com/aspnet-contrib/AspNet.Security.OpenId.Providers/actions/runs/12175534030/job/33959867500#step:7:47).

> Error: Error: Failed to persist attestation: Server Error - https://docs.github.com/rest/repos/repos#create-an-attestation

Links to the relevant workflow etc. can be found by following the actions log.

Rolling back to 1.4.4 fixes the build.

**Comment by bdehamer** [comment]
@martincostello thanks for the report. There is an issue we've identified in v2 that may result in the error you're seeing if you are using file globs for the `subject-path` input and you happen to have two subjects with the same name and digest.

We should have a fix out shortly. You may want to try again once we publish v2.0.1.

**Comment by bdehamer** [comment]
https://github.com/actions/attest-build-provenance/releases/tag/v2.0.1

**Comment by martincostello** [comment]
Thanks - will update here once the change is ingested through dependabot on whether the issue is resolved.

**Comment by martincostello** [comment]
Looks like the errors have gone away now 👍
