### ISSUE TITLE
Add technical spec regarding encoding and data storage

### ISSUE THREAD

**Issue by fmoessbauer** [actions/attest-build-provenance#62]
Hi, I tried to verify the build provenance using the cosign tool, but this does not seem to be compatible (yet).

Is there any technical spec regarding how the provenance attestation data is encoded and added to the container registry? From a quick tests, it looks like the the `attest-build-provenance` action does the following:

- The attestation data is added to the OCI v2 registry next to the image manifest (`application/vnd.oci.image.index.v1+json` for multi-arch images)
- The attestation data itself is a sigstore v0.3 bundle (`application/vnd.dev.sigstore.bundle.v0.3+json`), which links to the image manifest using an OCI Referrer
- The payload of the sigstore bundle contains the in-toto statement ( `https://in-toto.io/Statement/v1` )
- The predicate contains the gh action provenance data as `https://slsa.dev/provenance/v1`.

For verification, you need to do the following:

- get the digest of the container (the manifest / index)
- get the referrer by type for the manifest / index

The downloaded data is a sigstore v0.3 bundle, whereby the `.dsseEnvelope.payload` contains the in-toto Statement v1. The subject hereby points to the image manifest digest. The predicate contains the provenance v1 data and the signature can be checked by verifying the integrity of the DSSE.

**Comment by bdehamer** [comment]
Cosign does not yet support Sigstore bundles, but we're using the same [spec](https://github.com/sigstore/cosign/blob/main/specs/BUNDLE_SPEC.md) for storing bundles which will be implemented in cosign at some point.

**Comment by fmoessbauer** [comment]
Thanks for adding the reference to the readme. By that, I'll close the issue.
