### ISSUE TITLE
Build provenance not visible on Sigstore's Rekor

### ISSUE THREAD

**Issue by jul-sh** [actions/attest-build-provenance#69]
### Expected Behavior
Provenances created with this action can be found on sigstore, by searching for the subject's digest on `https://search.sigstore.dev/?hash=`. The corresponding entry there displays the full provenance. This is the case for provenances created using the [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator) action. Eg see this [workflow run](https://github.com/project-oak/oak/actions/runs/9023697076/job/24796309135) and its corresponding [rekor entry](https://search.sigstore.dev/?uuid=24296fb24b8ad77a06c983e3d820ef226b4eeda178204bc5a85d2fed89a0d5a8a953e4e7ff7aa930).

### Actual Behavior
One may find an entry for provenances created with this action. Eg see [this workflow run](https://github.com/thmsbinder/oak/attestations/810101) and its corresponding [entry on sigstore's rekor](https://search.sigstore.dev/?uuid=24296fb24b8ad77af62e1dc3fefeb97bb02b21ba31705a7ad628e363e72d9bec28d10369e24cc594), found via [this search](https://search.sigstore.dev/?hash=cd293be6cea034bd45a0352775a219ef5dc7825ce55d1f7dae9762d80ce64411). However, the entry on rekor does not show the actual provenance. 

cc @thmsbinder, @tiziano88

**Comment by bdehamer** [comment]
The difference in behavior between these two scenarios is by-design and is related to the [Rekor types](https://github.com/sigstore/rekor/tree/main/pkg/types#pluggable-types) which are being used to create the Rekor record.



![Image](https://github.com/actions/attest-build-provenance/assets/398027/1a84f799-2e70-45be-8710-7e1d425b590d)



The slsa-github-generator is using the [intoto](https://github.com/sigstore/rekor/tree/main/pkg/types/intoto) type, while the provenance action is using the newer [dsse](https://github.com/sigstore/rekor/tree/main/pkg/types/dsse) type.

Among [other things](https://github.com/sigstore/rekor/pull/1487) the `dsse` type was added to make clear that Rekor is solely meant to serve as an immutable record of the attestation's signature, NOT an API for attestation discovery.

By default, any attestations created by this action will automatically be persisted to the GH attestation store and can be retrieved from there at any time. You also have the option to push the generated attestation to an OCI registry.

**Comment by jul-sh** [comment]
@bdehamer Thanks for your quick response! Much appreciated.

What's your envisioned solution for attestation discovery? Currently GitHub attestations can only be retrieved directly, and not found by subject digest.

**Comment by bdehamer** [comment]
@jul-sh this hasn't yet been added to the official API documentation, but you can look-up your attestations by subject digest through the GH API.

```
GET /orgs/{org}/attestations/{digest}
```
or
```
GET /repos/{owner}/{repo}/attestations/{digest}
```

These are the same APIs which are currently being used by the [`gh attestation`](https://cli.github.com/manual/gh_attestation) CLI commands.

These endpoints should find their way into the official API docs by the time this feature GAs.
