### ISSUE TITLE
Actions jobs take a lot longer to finish when using this action

### ISSUE THREAD

**Issue by xPaw** [actions/attest-build-provenance#85]
Here's a build when using actions/attest-build-provenance: https://github.com/SteamDatabase/SteamTokenDumper/actions/runs/9176712362

And here's one when it was reverted: https://github.com/SteamDatabase/SteamTokenDumper/actions/runs/9180820690

For some reason it takes over 30 minutes for the job finish, but none of the steps take that long.

**Comment by bdehamer** [comment]
I think this may have been related to a [GitHub Actions incident](https://www.githubstatus.com/incidents/nj47vccwm2zj) which occurred during this time and not the `actions/attest-build-provenance` action.
